- type: job
  id: SecurityAdvisor
  name: job-name-security-advisor
  description: job-description-security-advisor
  playTimeTracker: JobSecurityAdvisor
  setPreference: false
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 6.5h
  supervisors: job-supervisors-hos
  guides:
  - Security
  - CorporateJudo
  access:
  - Security
  - Brig
  - Maintenance
  - External
  - Cryogenics
  - Command
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: SecurityStaff
