- type: job
  id: SecurityBodyguard
  name: job-name-security-bodyguard
  description: job-description-security-bodyguard
  playTimeTracker: JobSecurityBodyguard
  setPreference: false
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 3h
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-hos
  guides:
  - Security
  - CorporateJudo
  access:
  - Security
  - Brig
  - Maintenance
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: SecurityStaff
