# Hunters
  # SpacePol
- type: startingGear
  id: HunterAntagGear
  equipment:
    head: ClothingHeadHelmetSwat # maybe keep justice for shits and giggles?
    eyes: ClothingEyesGlassesSecurity
    neck: Dinkystar
    mask: ClothingHunterMaskGasSwat
    jumpsuit: ClothingUniformJumpsuitNanotrasen
    outerClothing: ClothingOuterArmourDurathread
    back: ClothingBackpackSatchelLeather
    shoes: ClothingShoesBootsJackFilled
    belt: ClothingBeltSecurityFilled
    id: HunterPDA
    pocket1: WeaponPistolMk58
    pocket2: WeaponLaserSidearm
    ears: ClothingHeadsetAltHunter
    gloves: ClothingHandsGlovesCombat
  storage:
    back:
    - BoxSurvivalSlotsSecurity
    - MagazinePistol
    - ForensicScanner
    - MedkitCombat

# Fugitives
  # Convict
- type: startingGear
  id: FugitiveAntagGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPrisoner
    shoes: ClothingShoesColorBlack
    belt: ClothingBeltStorageWaistbag
    id: IDCardTide
    pocket1: CombatKnife
    pocket2: SoapSyndie
  inhand:
  - SatchelFugitive
  storage:
    belt:
    - BarberScissors
    - Telecrystal25
